eod_prices:
  api:
    url: "https://wifeed.vn/api/du-lieu-gia-eod/full"
    api_key_var: "eod_prices_api_key"
    timeout: 30
    lookback_days: 7305

  db:
    postgres_conn_id: "keynum-central-pg"
    stock_list_table: "raw_vn_stock_data.stock_list"
    stock_list_code_column: "code"

    price_table: "raw_vn_stock_data.stock_prices"
    conflict_keys:
      - "mack"
      - "ngay"

    columns:
      - json_key: "mack"
        column: "mack"
      - json_key: "ngay"
        column: "ngay"
      - json_key: "open_root"
        column: "open_root"
      - json_key: "high_root"
        column: "high_root"
      - json_key: "low_root"
        column: "low_root"
      - json_key: "close_root"
        column: "close_root"
      - json_key: "volume_root"
        column: "volume_root"
      - json_key: "open_adjust"
        column: "open_adjust"
      - json_key: "high_adjust"
        column: "high_adjust"
      - json_key: "low_adjust"
        column: "low_adjust"
      - json_key: "close_adjust"
        column: "close_adjust"
      - json_key: "volume_adjust"
        column: "volume_adjust"
      - json_key: "avgprice"
        column: "avgprice"
      - json_key: "giatri_giaodich"
        column: "giatri_giaodich"
      - json_key: "ceilingprice"
        column: "ceilingprice"
      - json_key: "floorprice"
        column: "floorprice"
      - json_key: "changed"
        column: "changed"
      - json_key: "changedratio"
        column: "changedratio"
      - json_key: "kl_nn_ban"
        column: "kl_nn_ban"
      - json_key: "kl_nn_mua"
        column: "kl_nn_mua"
      - json_key: "gt_nn_ban"
        column: "gt_nn_ban"
      - json_key: "gt_nn_mua"
        column: "gt_nn_mua"
      - json_key: "lastupdate"
        column: "lastupdate"
      - json_key: "created_at"
        column: "created_at"
