financial_indicators_non_financial:
  api:
    url: "https://wifeed.vn/api/tai-chinh-doanh-nghiep/v2/chi-so-tai-chinh"
    api_key_var: "wifeed_api_key"
    timeout: 30
    type: "ttm"
    throttle_seconds: 1

  db:
    postgres_conn_id: "keynum-central-pg"
    stock_list_table: "raw_vn_stock_data.stock_list"
    stock_list_code_column: "code"

    target_table: "raw_vn_stock_data.financial_indicators_non_financial"
    conflict_keys:
      - "mack"
      - "nam"
      - "quy"

    columns:
      - "mack"
      - "quy"
      - "nam"
      - "tsck_nophaitra"
      - "duphonggiamgiackkd"
      - "nwc"
      - "fcff"
      - "fcfe"
      - "ebit"
      - "ebitda"
      - "tylethuesuat"
      - "nopat"
      - "ccc"
      - "bienlaigop"
      - "bienlaisauthue"
      - "bienlaiebit"
      - "bienlaiebitda"
      - "bienlaitruocthue"
      - "vongquaytaisan"
      - "vongquayphaithu"
      - "vongquaytonkho"
      - "vongquayphaitra"
      - "roa"
      - "roe"
      - "roic"
      - "khauhao_tscd"
      - "dongtien_hdkd_lnthuan"
      - "dongtien_hdkd_dtt"
      - "dongtien_hdkd_tts"
      - "dongtien_hdkd_vcsh"
      - "khtscd"
      - "capex"
      - "tile_tsdd_nguyengiatscd"
      - "duphongphaithu_phaithu_dn"
      - "tile_duphong_gghtk"
      - "tile_duphong_dttc_daihan"
      - "vldr"
      - "vldr_nwc"
      - "vldr_tsnh"
      - "vldr_tsdh"
      - "tt_dtt_yoy"
      - "tt_lng_yoy"
      - "tt_ebit_yoy"
      - "tt_ebitda_yoy"
      - "tt_lntt_yoy"
      - "tt_lnst_yoy"
      - "lnst_yoy"
      - "ln_hdkd_yoy"
      - "ln_hdtc_yoy"
      - "ln_ldlk_yoy"
      - "ln_khac_yoy"
      - "cpgiavon_yoy"
      - "cptaichinh_yoy"
      - "cpbh_yoy"
      - "cpqldn_yoy"
      - "tt_tts"
      - "tt_tsnh"
      - "tt_tsdh"
      - "ttdt_yoy"
      - "tvtgnh_yoy"
      - "ckkd_yoy"
      - "dttc_nganhan_yoy"
      - "dttc_daihan_yoy"
      - "cackhoanphaithu_yoy"
      - "htk_yoy"
      - "tscd_yoy"
      - "haomonluyke_yoy"
      - "bdsdautu_yoy"
      - "loithethuongmai_yoy"
      - "duphong_phaithu_yoy"
      - "tsdd_daihan_yoy"
      - "tscd_vohinh_yoy"
      - "duphong_giamgiackkd_yoy"
      - "duphong_giamgiahtk_yoy"
      - "duphong_dttc_daihan_yoy"
      - "tt_no"
      - "tt_nnh"
      - "tt_ndh"
      - "tt_vcsh"
      - "nguoimuatratruoc_yoy"
      - "phaitranguoiban_yoy"
      - "dt_chuathuchien_yoy"
      - "novay_yoy"
      - "nochiemdung_yoy"
      - "thangduvon_yoy"
      - "cpquy_yoy"
      - "ln_chuaphanphoi_yoy"
      - "lctt_hdkd_yoy"
      - "lctt_hddt_yoy"
      - "lctt_hdtc_yoy"
      - "lctt_trongky_yoy"
      - "khauhao_tscd_yoy"
      - "capex_yoy"
      - "dol"
      - "dfl"
      - "dtl"
      - "tongno_tongtaisan"
      - "congnonganhan_tongtaisan"
      - "congnodaihan_tongtaisan"
      - "tts_vonchu"
      - "novay_tts"
      - "novay_vonchu"
      - "novayrong_vonchu"
      - "ls_novay"
      - "thanhtoan_hienhanh"
      - "thanhtoan_nhanh"
      - "thanhtoan_tienmat"
      - "novay_ebitda"
      - "novay_dongtienhdkd"
      - "ebit_laivay"
      - "dongtien_hdkd_novay"
      - "dongtien_hdkd_laivay"
      - "tile_chiphigiavon"
      - "tile_chiphilaivay"
      - "tile_chiphibanhang"
      - "tile_chiphiquanly"
      - "tile_hangmuadiduong"
      - "tile_nguyenvatlieu"
      - "tile_congcudungcu"
      - "tile_chiphisanxuat"
      - "tile_thanhpham"
      - "tile_hanghoa"
      - "tile_hangguidiban"
      - "tile_hangtonkhokhac"
      - "tile_hanghoabds"
      - "tile_loinhuanhoatdongkinhdoanhchinh"
      - "tile_loinhuantaichinh"
      - "tile_lailoldlk"
      - "tile_loinhuankhac"
      - "tongno_tts_nam"
      - "congnonganhan_tts_nam"
      - "congnodaihan_tts_nam"
      - "tile_nguoimuatratruoc_nv"
      - "tile_phaitranguoiban_nv"
      - "tile_doanhthuchuathuchien_nv"
      - "tile_novay_nv"
      - "tile_nochiemdung_nv"
      - "tile_thangduvon_nv"
      - "tile_cophieuquy_nv"
      - "tile_loinhuanchuaphanpho_nv"
      - "tsnh_tts_dn"
      - "tvtd_tts_dn"
      - "tgnh_tts_dn"
      - "tile_ckkd"
      - "dttcnh_tts_dn"
      - "dttcdh_tts_dn"
      - "dttc_tts_dn"
      - "ckpt_tts_dn"
      - "htk_tts_dn"
      - "tscd_tts_dn"
      - "bdsdt_tts"
      - "lttm_tts"
      - "tile_tsdd_daihan"
      - "tile_tscd_vohinh"
      - "novay"
      - "ncav"
      - "ncav_ps"
      - "netcash"
      - "netcash_ps"
      - "p_ncav"
      - "p_ncp"
      - "p_fcff"
      - "p_fcfe"
      - "lng_tmcp"
      - "p_gp"
      - "p_lnw"
      - "lnwpershare"
      - "ev_ocf"
      - "ev_ebit"
      - "ev_ebitda"
      - "ev_fcff"
      - "nc_vh"
      - "lnw_vh"
      - "ev"
      - "ps"
      - "rev_per_share"
      - "vldr_vh"
      - "vcsh_nguonvon"
      - "nophaitra_vcsh"
      - "lnst_ctyme"
      - "lnst_ctyme_yoy"
      - "vcsh"
      - "vcsh_yoy"
      - "lctt_hdkd"
      - "lctt_hddt"
      - "lctt_hdtc"
      - "lntt"
      - "lntt_yoy"
      - "nophaitra"
      - "nophaitra_yoy"
      - "tts"
      - "tts_yoy"
      - "lnst"
      - "chiaccotuc_tienmat"
      - "tile_chiacotuc_cp"
      - "tt_lnst_kehoach_yoy"
      - "tt_lnst_lnstkehoach_yoy"
      - "tyle_hoanthanh_dt"
      - "tyle_hoanthanh_lnst"
      - "vonhoa"
      - "eps"
      - "bookvalue"
      - "bvps"
      - "pe"
      - "ep"
      - "pb"
      - "tang_truong_kv"
      - "pe_dp"
      - "peg"
      - "peg_dc"
      - "graham_1"
      - "graham_2"
      - "graham_3"
      - "tysuatcotuc"
      - "tl_chitracotucbangtien"
      - "dongtien_hdkd_tmcp"
      - "bq_tysuatcotuc"
      - "created_at"
      - "updated_at"
