ohlcv_15m:
  db:
    postgres_conn_id: "keynum-central-pg"
    source_table: "raw_crypto_data.ohlcv_3m"
    target_table: "raw_crypto_data.ohlcv_15m"
    symbol_quote: "USDT"
    conflict_keys: ["symbol", "exchange", "timestamp"]
    lookback_days: 3
    batch_days: 3
    bucket_minutes: 15
  schedule: "1/15 * * * *"
