stock_basic_info:
  api:
    url: "https://wifeed.vn/api/thong-tin-co-phieu/thong-tin-co-ban"  # cập nhật endpoint thực tế nếu khác
    api_key_var: "wifeed_api_key"
    timeout: 30

  db:
    postgres_conn_id: "vn_portfolio_db"
    stock_list_table: "raw_vn_stock_data.stock_list"
    stock_list_code_column: "code"

    target_table: "raw_vn_stock_data.stock_basic_info"
    conflict_keys:
      - "mack"

    # mapping json_key (từ API) -> column (trong DB)
    columns:
      - json_key: "mack"
        column: "mack"
      - json_key: "ten"
        column: "ten"
      - json_key: "name"
        column: "name"
      - json_key: "loai_hinh_cong_ty"
        column: "loai_hinh_cong_ty"
      - json_key: "san_niem_yet"
        column: "san_niem_yet"
      - json_key: "gioithieu"
        column: "gioithieu"
      - json_key: "diachi"
        column: "diachi"
      - json_key: "website"
        column: "website"
      - json_key: "nganhcap1"
        column: "nganhcap1"
      - json_key: "nganhcap2"
        column: "nganhcap2"
      - json_key: "nganhcap3"
        column: "nganhcap3"
      - json_key: "nganhcap4"
        column: "nganhcap4"
      - json_key: "ngayniemyet"
        column: "ngayniemyet"
      - json_key: "smg"
        column: "smg"
      - json_key: "volume_daily"
        column: "volume_daily"
      - json_key: "vol_tb_15ngay"
        column: "vol_tb_15ngay"
      - json_key: "vonhoa"
        column: "vonhoa"
      - json_key: "dif"
        column: "dif"
      - json_key: "dif_percent"
        column: "dif_percent"
      - json_key: "tong_tai_san"
        column: "tong_tai_san"
      - json_key: "soluongluuhanh"
        column: "soluongluuhanh"
      - json_key: "soluongniemyet"
        column: "soluongniemyet"
      - json_key: "cophieuquy"
        column: "cophieuquy"
      - json_key: "logo"
        column: "logo"
      - json_key: "created_at"
        column: "created_at"
      - json_key: "updated_at"
        column: "updated_at"
      - json_key: "donvikiemtoan"
        column: "donvikiemtoan"
